name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Deploy site
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history for semantic-release
          fetch-depth: 0
          token: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      # - name: Create Release Pull Request or Publish to npm
      - name: Deploy the site
        uses: changesets/action@65b9570
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
